/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Logins;

import java.sql.Date;
import java.util.Calendar;
import java.sql.*;

/**
 *
 * @author Dhruv Singh Rathore
 */
public class AddCentre extends javax.swing.JFrame {

    /**
     * Creates new form AddCentre
     */
    private String root = "root";
    private String pass = "MyNewPass";

    private String usernameCurrent;
    private String emailCurrent;
    private int isAdminCurrent;
    private int useridCurrent;
    private int bookedCurrent;
    private int centreFKCurrent;

    public AddCentre() {
        initComponents();
    }

    public AddCentre(String username,String email, int isAdmin, int userid, int booked, int centerFK) {
        
        initComponents();
        usernameCurrent = username;
        emailCurrent = email;
        isAdminCurrent = isAdmin;
        useridCurrent = userid;
        bookedCurrent = booked;
        centreFKCurrent = centerFK;

        errorCentreEmpty.setVisible(false);
        centreAddSuccess.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        centreNF = new javax.swing.JTextField();
        centreAF = new javax.swing.JTextField();
        centreDF = new com.toedter.calendar.JDateChooser();
        centreSF = new javax.swing.JFormattedTextField();
        submitCentreButton1 = new javax.swing.JButton();
        errorCentreEmpty = new javax.swing.JLabel();
        centreAddSuccess = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 10));
        jPanel1.setMinimumSize(new java.awt.Dimension(300, 300));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 400));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lato Black", 0, 14)); // NOI18N
        jLabel1.setText("Stock");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 230, 120, 20);

        jLabel2.setFont(new java.awt.Font("Lato Black", 1, 24)); // NOI18N
        jLabel2.setText("Add a Center");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 40, 180, 40);

        jLabel3.setFont(new java.awt.Font("Lato Black", 0, 14)); // NOI18N
        jLabel3.setText("Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 110, 120, 20);

        jLabel4.setFont(new java.awt.Font("Lato Black", 0, 14)); // NOI18N
        jLabel4.setText("Address");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 150, 120, 20);

        jLabel5.setFont(new java.awt.Font("Lato Black", 0, 14)); // NOI18N
        jLabel5.setText("Date");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 190, 120, 20);

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton);
        backButton.setBounds(360, 50, 100, 30);
        jPanel1.add(centreNF);
        centreNF.setBounds(180, 110, 140, 30);
        jPanel1.add(centreAF);
        centreAF.setBounds(180, 150, 140, 30);
        jPanel1.add(centreDF);
        centreDF.setBounds(180, 189, 140, 30);

        centreSF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        centreSF.setText("0");
        jPanel1.add(centreSF);
        centreSF.setBounds(180, 230, 140, 30);

        submitCentreButton1.setText("Submit");
        submitCentreButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitCentreButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(submitCentreButton1);
        submitCentreButton1.setBounds(180, 280, 140, 30);

        errorCentreEmpty.setFont(new java.awt.Font("Lato Black", 0, 14)); // NOI18N
        errorCentreEmpty.setForeground(new java.awt.Color(255, 102, 51));
        errorCentreEmpty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorCentreEmpty.setText("Fill all the fields!");
        errorCentreEmpty.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        jPanel1.add(errorCentreEmpty);
        errorCentreEmpty.setBounds(30, 280, 140, 30);

        centreAddSuccess.setFont(new java.awt.Font("Lato Black", 0, 14)); // NOI18N
        centreAddSuccess.setForeground(new java.awt.Color(255, 102, 51));
        centreAddSuccess.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        centreAddSuccess.setText("Centre added!");
        centreAddSuccess.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        jPanel1.add(centreAddSuccess);
        centreAddSuccess.setBounds(180, 320, 140, 30);

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
        SlotMain window = new SlotMain(usernameCurrent, emailCurrent, isAdminCurrent, useridCurrent, bookedCurrent, centreFKCurrent);
        window.setVisible(true);



    }//GEN-LAST:event_backButtonActionPerformed

    private void submitCentreButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitCentreButton1ActionPerformed
        // TODO add your handling code here:
        
        
        String name = centreNF.getText();
        String address = centreAF.getText();
        String stockString = centreSF.getText();
        java.util.Date date = centreDF.getDate();

        errorCentreEmpty.setVisible(false);
        centreAddSuccess.setVisible(false);

        if(name.isEmpty() || address.isEmpty()|| stockString.isEmpty() || date == null){
            errorCentreEmpty.setVisible(true);
            // System.out.println("Fill all the fields dialog box!");
            return;
        }
        Calendar cal = Calendar.getInstance();
        cal.setTime(date);
        int month = cal.get(Calendar.MONTH);
        int day = cal.get(Calendar.DAY_OF_WEEK);
        int year = cal.get(Calendar.YEAR);
        month += 1;
        int stock = Integer.parseInt(centreSF.getText());
        String formattedDate = year+"-"+month+"-"+day;
        // System.out.println("Day: " + day);
        // System.out.println("Month: " + month);
        // System.out.println("Year: " + year);

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");  
            Connection con=DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/vaccinedb?zeroDateTimeBehavior=CONVERT_TO_NULL",root, pass);  
            
            Statement stmt=con.createStatement();  
            String query = " INSERT INTO vaccinedb.centres (adminID, name, address, `date`, stock)"
                + " VALUES (?, ?, ?, ?, ?)";

            PreparedStatement preparedStmt = con.prepareStatement(query);
                preparedStmt.setInt(1, useridCurrent);
                preparedStmt.setString(2, name);
                preparedStmt.setString(3, address);
                preparedStmt.setString(4, formattedDate);
                preparedStmt.setInt(5, stock);
                preparedStmt.execute();
                con.close();

                centreAddSuccess.setVisible(true);
                // System.out.println("Added a new centre successfully!");
                this.dispose();
                SlotMain window = new SlotMain(usernameCurrent, emailCurrent, isAdminCurrent, useridCurrent, bookedCurrent, centreFKCurrent);
                window.setVisible(true);
           
        } catch (Exception e) {
            System.out.println("New Center Creation Exception: " + e);
        }




    }//GEN-LAST:event_submitCentreButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCentre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCentre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCentre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCentre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCentre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField centreAF;
    private javax.swing.JLabel centreAddSuccess;
    private com.toedter.calendar.JDateChooser centreDF;
    private javax.swing.JTextField centreNF;
    private javax.swing.JFormattedTextField centreSF;
    private javax.swing.JLabel errorCentreEmpty;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton submitCentreButton1;
    // End of variables declaration//GEN-END:variables
}
