/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Logins;
import java.sql.*;
/**
 *
 * @author Dhruv Singh Rathore
 */

public class Login extends javax.swing.JFrame {
    /**
     * Creates new form Login
     */

    private String root = "root";
    private String pass = "MyNewPass";
    
    public Login() {
        initComponents();
        signUpPanel.setVisible(false);
        errorLoginInvalid.setVisible(false);
        errorLoginEmpty.setVisible(false);
        errorSignUpEmpty.setVisible(false);
        errorSignUpEmail.setVisible(false);
        signUpSuccess.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        loginPF = new javax.swing.JPasswordField();
        loginEF = new javax.swing.JTextField();
        signUpView = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        errorLoginInvalid = new javax.swing.JLabel();
        errorLoginEmpty = new javax.swing.JLabel();
        signUpPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        signUpPF = new javax.swing.JPasswordField();
        signUpEF = new javax.swing.JTextField();
        loginView = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        signUpButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        signUpUF = new javax.swing.JTextField();
        errorSignUpEmpty = new javax.swing.JLabel();
        errorSignUpEmail = new javax.swing.JLabel();
        signUpSuccess = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 550));
        setPreferredSize(new java.awt.Dimension(650, 550));
        getContentPane().setLayout(new java.awt.CardLayout());

        loginPanel.setBackground(new java.awt.Color(102, 255, 255));
        loginPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 15));
        loginPanel.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lato Black", 0, 18)); // NOI18N
        jLabel1.setText("New user?");
        loginPanel.add(jLabel1);
        jLabel1.setBounds(40, 340, 130, 20);

        jLabel2.setFont(new java.awt.Font("Lato Black", 1, 36)); // NOI18N
        jLabel2.setText("Vaccination Slot Booking");
        loginPanel.add(jLabel2);
        jLabel2.setBounds(40, 30, 450, 50);

        jLabel3.setFont(new java.awt.Font("Lato Black", 0, 24)); // NOI18N
        jLabel3.setText("Log-in");
        loginPanel.add(jLabel3);
        jLabel3.setBounds(40, 120, 100, 30);

        jLabel4.setFont(new java.awt.Font("Lato Black", 0, 18)); // NOI18N
        jLabel4.setText("Email");
        loginPanel.add(jLabel4);
        jLabel4.setBounds(40, 170, 140, 30);
        loginPanel.add(loginPF);
        loginPF.setBounds(220, 210, 140, 30);
        loginPanel.add(loginEF);
        loginEF.setBounds(220, 170, 140, 30);

        signUpView.setText("Sign Up");
        signUpView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpViewActionPerformed(evt);
            }
        });
        loginPanel.add(signUpView);
        signUpView.setBounds(220, 340, 90, 21);

        jLabel5.setFont(new java.awt.Font("Lato Black", 0, 18)); // NOI18N
        jLabel5.setText("Password");
        loginPanel.add(jLabel5);
        jLabel5.setBounds(40, 210, 140, 30);

        loginButton.setText("Log In");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        loginPanel.add(loginButton);
        loginButton.setBounds(220, 250, 90, 21);

        errorLoginInvalid.setFont(new java.awt.Font("Lato Black", 0, 14)); // NOI18N
        errorLoginInvalid.setForeground(new java.awt.Color(255, 102, 51));
        errorLoginInvalid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorLoginInvalid.setText("Invalid Credentials!");
        errorLoginInvalid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        loginPanel.add(errorLoginInvalid);
        errorLoginInvalid.setBounds(220, 280, 140, 30);

        errorLoginEmpty.setFont(new java.awt.Font("Lato Black", 0, 14)); // NOI18N
        errorLoginEmpty.setForeground(new java.awt.Color(255, 102, 51));
        errorLoginEmpty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorLoginEmpty.setText("Fill all the fields!");
        errorLoginEmpty.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        loginPanel.add(errorLoginEmpty);
        errorLoginEmpty.setBounds(220, 280, 140, 30);

        getContentPane().add(loginPanel, "card2");

        signUpPanel.setBackground(new java.awt.Color(102, 255, 255));
        signUpPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 15));
        signUpPanel.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Lato Black", 0, 18)); // NOI18N
        jLabel6.setText("Already a user?");
        signUpPanel.add(jLabel6);
        jLabel6.setBounds(40, 340, 130, 20);

        jLabel7.setFont(new java.awt.Font("Lato Black", 1, 36)); // NOI18N
        jLabel7.setText("Vaccination Slot Booking");
        signUpPanel.add(jLabel7);
        jLabel7.setBounds(40, 30, 450, 50);

        jLabel8.setFont(new java.awt.Font("Lato Black", 0, 24)); // NOI18N
        jLabel8.setText("Sign Up");
        signUpPanel.add(jLabel8);
        jLabel8.setBounds(40, 120, 100, 30);

        jLabel9.setFont(new java.awt.Font("Lato Black", 0, 18)); // NOI18N
        jLabel9.setText("Email");
        signUpPanel.add(jLabel9);
        jLabel9.setBounds(40, 210, 140, 30);
        signUpPanel.add(signUpPF);
        signUpPF.setBounds(220, 250, 140, 30);
        signUpPanel.add(signUpEF);
        signUpEF.setBounds(220, 210, 140, 30);

        loginView.setText("Log In");
        loginView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginViewActionPerformed(evt);
            }
        });
        signUpPanel.add(loginView);
        loginView.setBounds(220, 340, 90, 21);

        jLabel10.setFont(new java.awt.Font("Lato Black", 0, 18)); // NOI18N
        jLabel10.setText("Password");
        signUpPanel.add(jLabel10);
        jLabel10.setBounds(40, 250, 140, 30);

        signUpButton.setText("Sign Up");
        signUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtonActionPerformed(evt);
            }
        });
        signUpPanel.add(signUpButton);
        signUpButton.setBounds(220, 290, 90, 21);

        jLabel11.setFont(new java.awt.Font("Lato Black", 0, 18)); // NOI18N
        jLabel11.setText("Username");
        signUpPanel.add(jLabel11);
        jLabel11.setBounds(40, 170, 140, 30);
        signUpPanel.add(signUpUF);
        signUpUF.setBounds(220, 170, 140, 30);

        errorSignUpEmpty.setFont(new java.awt.Font("Lato Black", 0, 14)); // NOI18N
        errorSignUpEmpty.setForeground(new java.awt.Color(255, 102, 51));
        errorSignUpEmpty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorSignUpEmpty.setText("Fill all the fields!");
        errorSignUpEmpty.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        signUpPanel.add(errorSignUpEmpty);
        errorSignUpEmpty.setBounds(220, 120, 140, 30);

        errorSignUpEmail.setFont(new java.awt.Font("Lato Black", 0, 14)); // NOI18N
        errorSignUpEmail.setForeground(new java.awt.Color(255, 102, 51));
        errorSignUpEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorSignUpEmail.setText("Email Already Exists!");
        errorSignUpEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        signUpPanel.add(errorSignUpEmail);
        errorSignUpEmail.setBounds(380, 210, 150, 30);

        signUpSuccess.setFont(new java.awt.Font("Lato Black", 0, 14)); // NOI18N
        signUpSuccess.setForeground(new java.awt.Color(255, 102, 51));
        signUpSuccess.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signUpSuccess.setText("Sign Up Successful!");
        signUpSuccess.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 51)));
        signUpPanel.add(signUpSuccess);
        signUpSuccess.setBounds(220, 370, 150, 30);

        getContentPane().add(signUpPanel, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signUpViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpViewActionPerformed
        // TODO add your handling code here:
        loginPanel.setVisible(false);
        signUpPanel.setVisible(true);
        errorSignUpEmpty.setVisible(false);
        errorSignUpEmail.setVisible(false);
        signUpSuccess.setVisible(false);
        errorLoginEmpty.setVisible(false);
        errorLoginInvalid.setVisible(false);
       
    }//GEN-LAST:event_signUpViewActionPerformed

    private void loginViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginViewActionPerformed
        // TODO add your handling code here:
        loginPanel.setVisible(true);
        signUpPanel.setVisible(false);
        errorSignUpEmpty.setVisible(false);
        errorSignUpEmail.setVisible(false);
        signUpSuccess.setVisible(false);
        errorLoginEmpty.setVisible(false);
        errorLoginInvalid.setVisible(false);
        
    }//GEN-LAST:event_loginViewActionPerformed

    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpButtonActionPerformed
        // TODO add your handling code here:
        String username = signUpUF.getText();
        String email = signUpEF.getText();
        String password = new String(signUpPF.getPassword());        
        errorSignUpEmpty.setVisible(false);
        errorSignUpEmail.setVisible(false);
        errorSignUpEmail.setVisible(false);


        if(username.isEmpty() || email.isEmpty()|| password.isEmpty()){
            errorSignUpEmpty.setVisible(true);

            // System.out.println("Fill all the fields dialog box!");
            return;
        }

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");  
            Connection con=DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/vaccinedb?zeroDateTimeBehavior=CONVERT_TO_NULL",root,pass);  
            
            Statement stmt=con.createStatement();  
            String sql = "select email from users;";
            ResultSet rs=stmt.executeQuery(sql);  
            // ResultSetMetaData rsmd=rs.getMetaData();

            while(rs.next()){
                System.out.println(rs.getString(1));
                if(rs.getString(1).equals(email)){
                    errorSignUpEmail.setVisible(true);
                    // System.out.println("Email Already exists!");
                    return;
                }
            }

            System.out.println("Creating a new user here!");
            try{
                String query = " INSERT INTO vaccinedb.users (username, email, password, `isAdmin`)"
                + " VALUES (?, ?, MD5(?), DEFAULT)";

                PreparedStatement preparedStmt = con.prepareStatement(query);
                preparedStmt.setString(1, username);
                preparedStmt.setString(2, email);
                preparedStmt.setString(3, password);
                preparedStmt.execute();
                con.close();
                signUpEF.setText("");
                signUpUF.setText("");
                signUpPF.setText("");
                signUpSuccess.setVisible(true);
                // System.out.println("Signed up successfully!");
                return;
            }
            catch (Exception e) {
                System.out.println("Exception: " + e);
            }


        } catch (Exception e) {
            System.out.println("Exception: " + e);
        }


    }//GEN-LAST:event_signUpButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        String email = loginEF.getText();
        String password = new String(loginPF.getPassword());        
       
        errorLoginEmpty.setVisible(false);
        errorLoginInvalid.setVisible(false);

        if( email.isEmpty()|| password.isEmpty()){

            errorLoginEmpty.setVisible(true);
            // System.out.println("Fill all the fields dialog box!");
            return;
        }
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");  
            Connection con=DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/vaccinedb?zeroDateTimeBehavior=CONVERT_TO_NULL",root,pass);  
            
            Statement stmt=con.createStatement();  
            String sql = "select * from users where email = '"+email+"' and password = MD5('"+password+"');";
            ResultSet rs=stmt.executeQuery(sql); 
            // ResultSetMetaData rsmd=rs.getMetaData();
            if(rs.next()){
                // System.out.println("Credentials Match!");
                this.dispose();
                SlotMain window = new SlotMain(rs.getString(2), email, rs.getInt(5), rs.getInt(1), rs.getInt(7), rs.getInt(6));
                window.setVisible(true);
            }
            else{
                errorLoginInvalid.setVisible(true);
                // System.out.println("Invalid Login Information!");
            }
            
        } catch (Exception e) {
            System.out.println("Exception: " + e);
        }


    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorLoginEmpty;
    private javax.swing.JLabel errorLoginInvalid;
    private javax.swing.JLabel errorSignUpEmail;
    private javax.swing.JLabel errorSignUpEmpty;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField loginEF;
    private javax.swing.JPasswordField loginPF;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JButton loginView;
    private javax.swing.JButton signUpButton;
    private javax.swing.JTextField signUpEF;
    private javax.swing.JPasswordField signUpPF;
    private javax.swing.JPanel signUpPanel;
    private javax.swing.JLabel signUpSuccess;
    private javax.swing.JTextField signUpUF;
    private javax.swing.JButton signUpView;
    // End of variables declaration//GEN-END:variables
}
