/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Logins;
import java.sql.*;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Dhruv Singh Rathore
 */
public class SlotMain extends javax.swing.JFrame {

    /**
     * Creates new form SlotMain
     */
    private String root = "root";
    private String pass = "MyNewPass";
    
    private String usernameCurrent;
    private String emailCurrent;
    private int isAdminCurrent;
    private int useridCurrent;
    private int bookedCurrent;
    private int centreFKCurrent;

    public SlotMain() {
        initComponents();
        System.out.println("No arguments passed frame.");
    }

    public SlotMain(String username,String email, int isAdmin, int userid, int booked, int centreFK) {
        // System.out.println("LOGGED IN WITH: " + email);
        // System.out.println("ADMIN: " + isAdmin);
        usernameCurrent = username;
        emailCurrent = email;
        isAdminCurrent = isAdmin;
        useridCurrent = userid;
        bookedCurrent = booked;
        centreFKCurrent = centreFK;

        initComponents();
        listCentres(jPanel3, userid);
        userLabel.setText(username);
        
        errorBooked.setVisible(false);
        bookedSuccess.setVisible(false);

        if(isAdmin == 0){
            addCentreButton.setVisible(false);
            adminLabel.setVisible(false);
        }

        if(bookedCurrent == 0){
            bookedSlotLabel.setText("NOT BOOKED!");
        }
        else{
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");  
                Connection con=DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/vaccinedb?zeroDateTimeBehavior=CONVERT_TO_NULL",root,pass);  
                
                Statement stmt=con.createStatement();  
                ResultSet rs = stmt.executeQuery("SELECT * FROM centres WHERE centreid=" + centreFK + " LIMIT 1;");
                rs.next();
                bookedSlotLabel.setText(rs.getString(2));


            } catch (Exception e) {
                System.out.println("Finding Centre Exception: " + e);
                //TODO: handle exception
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        userLabel = new javax.swing.JLabel();
        addCentreButton = new javax.swing.JButton();
        bookedSlotLabel = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        slotLabel = new javax.swing.JLabel();
        adminLabel = new javax.swing.JLabel();
        errorBooked = new javax.swing.JLabel();
        bookedSuccess = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(825, 425));
        setPreferredSize(new java.awt.Dimension(825, 425));
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 10));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 550));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 550));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0};
        jPanel1Layout.rowHeights = new int[] {0, 5, 0};
        jPanel1.setLayout(jPanel1Layout);

        jPanel2.setBackground(new java.awt.Color(255, 153, 51));
        jPanel2.setMinimumSize(new java.awt.Dimension(650, 50));
        jPanel2.setPreferredSize(new java.awt.Dimension(650, 50));
        jPanel2.setLayout(null);

        userLabel.setFont(new java.awt.Font("Lato Black", 1, 18)); // NOI18N
        userLabel.setText("[USERNAME]");
        jPanel2.add(userLabel);
        userLabel.setBounds(10, 10, 130, 20);

        addCentreButton.setText("Add a new centre");
        addCentreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCentreButtonActionPerformed(evt);
            }
        });
        jPanel2.add(addCentreButton);
        addCentreButton.setBounds(360, 10, 140, 33);

        bookedSlotLabel.setFont(new java.awt.Font("Lato Black", 1, 12)); // NOI18N
        bookedSlotLabel.setText("<centre_name>");
        jPanel2.add(bookedSlotLabel);
        bookedSlotLabel.setBounds(40, 30, 110, 30);

        logoutButton.setText("Log Out");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        jPanel2.add(logoutButton);
        logoutButton.setBounds(510, 10, 90, 33);

        slotLabel.setFont(new java.awt.Font("Lato Black", 1, 12)); // NOI18N
        slotLabel.setText("Slot: ");
        jPanel2.add(slotLabel);
        slotLabel.setBounds(10, 30, 30, 30);

        adminLabel.setFont(new java.awt.Font("Lato Black", 1, 12)); // NOI18N
        adminLabel.setText("[ADMIN]");
        jPanel2.add(adminLabel);
        adminLabel.setBounds(140, 10, 50, 20);

        errorBooked.setFont(new java.awt.Font("Lato Black", 0, 14)); // NOI18N
        errorBooked.setForeground(new java.awt.Color(51, 51, 255));
        errorBooked.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorBooked.setText("Already Booked!");
        errorBooked.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 5));
        jPanel2.add(errorBooked);
        errorBooked.setBounds(210, 10, 140, 40);

        bookedSuccess.setFont(new java.awt.Font("Lato Black", 0, 14)); // NOI18N
        bookedSuccess.setForeground(new java.awt.Color(51, 51, 255));
        bookedSuccess.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bookedSuccess.setText("Booked Succesfully!");
        bookedSuccess.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 5));
        jPanel2.add(bookedSuccess);
        bookedSuccess.setBounds(200, 10, 160, 40);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        jPanel1.add(jPanel2, gridBagConstraints);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(650, 550));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(650, 550));

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(jPanel3);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 54;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.7;
        jPanel1.add(jScrollPane1, gridBagConstraints);

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCentreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCentreButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        AddCentre window = new AddCentre(usernameCurrent, emailCurrent, isAdminCurrent, useridCurrent, bookedCurrent, centreFKCurrent);
        window.setVisible(true);

    }//GEN-LAST:event_addCentreButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Login().setVisible(true);

    }//GEN-LAST:event_logoutButtonActionPerformed

    

    private void listCentres(JPanel mainDisplay, int userid){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");  
            Connection con=DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/vaccinedb?zeroDateTimeBehavior=CONVERT_TO_NULL",root,pass);  
            
            Statement stmt=con.createStatement();  
            ResultSet rsCount = stmt.executeQuery("SELECT COUNT(*) FROM centres;");
            rsCount.next();
            int count = rsCount.getInt(1);
            JPanel centrePanel[] = new JPanel[count];
            JLabel centreName[] = new JLabel[count];
            JLabel centreAddress[] = new JLabel[count];
            JLabel centreDate[] = new JLabel[count];
            JButton centreButton[] = new JButton[count];

            String centreNameList[] = new String[count];
            String centreAdminID[] = new String[count];
            Integer centreFK[] = new Integer[count];
            String centreAddressList[] = new String[count];
            String centreDateList[] = new String[count];
            Integer centreStock[] = new Integer[count];

            ActionListener listener = new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    JButton button = (JButton) e.getSource();
                    // System.out.println(button.getName());
        
                    errorBooked.setVisible(false);
                    bookedSuccess.setVisible(false);

                    try {
                        Class.forName("com.mysql.cj.jdbc.Driver");  
                        Connection con=DriverManager.getConnection(
                        "jdbc:mysql://localhost:3306/vaccinedb?zeroDateTimeBehavior=CONVERT_TO_NULL",root,pass);  
        
                        Statement stmt=con.createStatement();  
                        ResultSet rs = stmt.executeQuery("SELECT booked FROM users WHERE userid="+userid+";");
                        rs.next();
                        if(rs.getInt(1) == 1){
                            errorBooked.setVisible(true);
                            // System.out.println("Already booked!");
                            return;
                        }

                        int i = Integer.parseInt(button.getName());
                        stmt.executeUpdate("UPDATE users SET centre = "+ centreFK[i] +", booked=" + 1 + " WHERE userid="+userid+ ";");
                        bookedCurrent = 1;
                        centreFKCurrent = centreFK[i];
                        bookedSlotLabel.setText(centreNameList[i]);
                        bookedSuccess.setVisible(true);
                        con.close();
                        return;

                    } catch (Exception error) {
                        System.out.println("BUTTON EXCEPTION: " + error);
                    }
        
                }
            };

            ResultSet rs=stmt.executeQuery("select * from centres;");  
            ResultSetMetaData rsmd=rs.getMetaData();
            int i = 0;
            while(rs.next()){
                centreAdminID[i] = rs.getString(1);
                centreNameList[i] = rs.getString(2);
                centreFK[i] = rs.getInt(3);
                centreAddressList[i] = rs.getString(4);
                centreDateList[i] = rs.getString(5);
                centreStock[i] = rs.getInt(6);
                i++;
            }

            for(i = 0; i < count; i++){
                centreButton[i] = new JButton();
                centreDate[i] = new JLabel();
                centreName[i] = new JLabel();
                centreAddress[i] = new JLabel();
                centrePanel[i] = new JPanel();
                centreButton[i].addActionListener(listener);
                centreButton[i].setName(""+i);

                centrePanel[i].setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
                centrePanel[i].setLayout(null);
                centrePanel[i].setBackground(new java.awt.Color(255, 153, 153));


                centreButton[i].setText("Book");
                centreButton[i].setBounds(430, 20, 150, 60);


                centreDate[i].setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
                centreDate[i].setText(centreDateList[i]);
                centreDate[i].setBounds(270, 50, 110, 20);

                centreName[i].setText(centreNameList[i]);
                centreName[i].setBounds(20, 20, 179, 27);
                centreName[i].setFont(new java.awt.Font("Trebuchet MS", 1, 18));

                centreAddress[i].setText(centreAddressList[i]);
                centreAddress[i].setFont(new java.awt.Font("Verdana", 0, 10));
                centreAddress[i].setBounds(20, 50, 230, 20);


                centrePanel[i].add(centreButton[i]);
                centrePanel[i].add(centreName[i]);
                centrePanel[i].add(centreAddress[i]);
                centrePanel[i].add(centreDate[i]);

                // centrePanel[i].setBounds(10, 120, 558, 105);
                // centrePanel[i].setVisible(true);

                centrePanel[i].setPreferredSize(new java.awt.Dimension(600, 100));

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(centrePanel[i]);
                centrePanel[i].setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                    jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 600, Short.MAX_VALUE)
                );
                jPanel2Layout.setVerticalGroup(
                    jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 100, Short.MAX_VALUE)
                );

                mainDisplay.add(centrePanel[i]);


            }
            // System.out.println("WORKING");

        }
        catch(Exception e){
            System.out.println(e);
        }
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SlotMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SlotMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SlotMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SlotMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SlotMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCentreButton;
    private javax.swing.JLabel adminLabel;
    private javax.swing.JLabel bookedSlotLabel;
    private javax.swing.JLabel bookedSuccess;
    private javax.swing.JLabel errorBooked;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel slotLabel;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
